package org.edutech.servicioss.infraestructura.enums;

public enum Categoria {
  DESARROLLO_WEB,
  DESARROLLO_DE_APLICACIONES_MOVILES,
  CIENCIA_DE_DATOS_Y_ANALISIS_DE_DATOS,
  DESARROLLO_DE_SOFTWARE,
  SEGURIDAD_INFORMATICA_Y_CIBERSEGURIDAD;

}
